"use client";
import {useEffect,useState} from 'react';
const blank={slug:'',name:'',price:0,collection:'Studio',category:'Lifestyle',colorway:'',description:'',images:['/assets/products/studio-runner-oxblood/01-main.png'],sizes:[39,40,41,42,43,44,45].map(size=>({size,stock:0})),published:true};
export default function ProductManager(){const [items,setItems]=useState([]),[form,setForm]=useState(null),[creating,setCreating]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/catalog?admin=1');const b=await r.json();if(!r.ok)throw Error(b.error);setItems(b.products)}
 useEffect(()=>{const controller=new AbortController();fetch('/api/catalog?admin=1',{signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);return b.products}).then(setItems).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/catalog',{method:creating?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw Error(b.error);await load();setForm(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function remove(p){if(!confirm(`Remove ${p.name} from the catalog? Existing orders will remain.`))return;try{const r=await fetch('/api/catalog',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug:p.slug})});if(!r.ok)throw Error('Delete failed');await load()}catch(e){setError(e.message)}}
 return <section className="panel product-manager"><div className="panel-head"><h2>Product catalog</h2><button onClick={()=>{setCreating(true);setForm({...blank})}}>+ New product</button></div>{error&&<p role="alert" className="admin-error">{error}</p>}{items.map(p=><div className="manager-row" key={p.slug}><div><b>{p.name}</b><small>{p.colorway} · {p.published?'Published':'Draft'}</small></div><span>€{p.price}</span><button onClick={()=>{setCreating(false);setForm(p)}}>Edit</button><button onClick={()=>remove(p)}>Delete</button></div>)}{form&&<form onSubmit={save} className="manager-form"><h2>{creating?'Create product':'Edit product'}</h2>{['name','slug','collection','category','colorway'].map(key=><label key={key}>{key}<input required value={form[key]} disabled={key==='slug'&&!creating} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Price (€)<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Local image paths (one per line)<textarea value={form.images.join('\n')} onChange={e=>setForm({...form,images:e.target.value.split('\n')})}/></label><p>Stock is physical on-hand quantity. Active orders reserve units; reserved stock cannot be removed.</p><div className="manager-sizes">{form.sizes.map((s,i)=><label key={s.size}>EU {s.size} · {s.reserved||0} reserved<input type="number" min="0" value={s.stock} onChange={e=>setForm({...form,sizes:form.sizes.map((x,j)=>j===i?{...x,stock:Number(e.target.value)}:x)})}/></label>)}</div><label><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Published</label><button disabled={busy}>{busy?'Saving…':'Save product'}</button><button type="button" onClick={()=>setForm(null)}>Cancel</button></form>}</section>
}
