"use client";
import NewsletterForm from "./NewsletterForm";
import Image from "next/image";import Link from "next/link";import {useSelectedLayoutSegments} from "next/navigation";import {useEffect,useState} from "react";import {products,money} from "@/data/products";import {useCommerce} from "@/context/CommerceContext";
export default function StorefrontShell({children}){const segments=useSelectedLayoutSegments();const admin=segments.includes("dashboard");const [menu,setMenu]=useState(false);const [query,setQuery]=useState("");const c=useCommerce();const [catalog,setCatalog]=useState(products);useEffect(()=>{if(!c.searchOpen)return;const controller=new AbortController();fetch("/api/catalog",{signal:controller.signal}).then(r=>r.ok?r.json():null).then(b=>{if(b)setCatalog(b.products)}).catch(()=>{});return()=>controller.abort()},[c.searchOpen]);useEffect(()=>{document.body.style.overflow=menu||c.searchOpen||c.cartOpen?"hidden":"";return()=>{document.body.style.overflow=""}},[menu,c.searchOpen,c.cartOpen]);if(admin)return children;const results=catalog.filter(p=>`${p.name} ${p.colorway} ${p.collection}`.toLowerCase().includes(query.toLowerCase())).slice(0,6);
return <><header className="global-nav"><button className="menu-trigger" onClick={()=>setMenu(true)} aria-label="Open menu"><i/><i/></button><Link href="/" className="logo">ARCHIVE<span>/</span>SUPPLY</Link><nav><Link href="/new-drops">New drops</Link><Link href="/men">Men</Link><Link href="/women">Women</Link><Link href="/collections">Collections</Link></nav><div className="nav-tools"><button onClick={()=>c.setSearchOpen(true)}>Search</button><Link href="/wishlist" aria-label={`Wishlist with ${c.wishlist.length} saved items`}>♡ {c.wishlist.length||""}</Link><button onClick={()=>c.setCartOpen(true)}>Bag <b>{String(c.count).padStart(2,"0")}</b></button></div></header>{children}
{menu&&<div className="menu-overlay" role="dialog" aria-modal="true"><button onClick={()=>setMenu(false)}>Close ×</button><nav>{[["New drops","/new-drops"],["Men","/men"],["Women","/women"],["Sneakers","/shop"],["Collections","/collections"],["About","/about"]].map(([x,url],i)=><Link href={url} onClick={()=>setMenu(false)} key={x}><span>0{i+1}</span>{x}</Link>)}</nav></div>}
{c.searchOpen&&<div className="search-overlay" role="dialog" aria-modal="true"><button className="overlay-close" onClick={()=>c.setSearchOpen(false)}>Close ×</button><label htmlFor="global-search">SEARCH THE ARCHIVE</label><input id="global-search" value={query} onChange={e=>setQuery(e.target.value)} autoFocus placeholder="STYLE, COLOUR OR COLLECTION"/><div className="search-results">{results.map(p=><Link href={`/product/${p.slug}`} onClick={()=>c.setSearchOpen(false)} key={p.slug}><Image src={p.images[0]} alt="" width={120} height={90}/><span><small>{p.collection}</small>{p.name}</span><b>{money(p.price)}</b></Link>)}</div></div>}
{c.cartOpen&&<div className="drawer-backdrop" onClick={()=>c.setCartOpen(false)}><aside className="cart-drawer-new" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>YOUR BAG <span>{c.count}</span></h2><button onClick={()=>c.setCartOpen(false)}>Close ×</button></div>{!c.cart.length?<div className="empty-cart"><p>Your rotation is empty.</p><Link href="/shop" onClick={()=>c.setCartOpen(false)}>Shop sneakers ↗</Link></div>:<><div className="cart-lines">{c.cart.map(item=><div className="cart-line" key={`${item.slug}-${item.size}`}><Image src={item.image} alt="" width={110} height={90}/><div><b>{item.name}</b><span>{item.colorway}<br/>EU {item.size}</span><div className="qty"><button onClick={()=>c.update(item.slug,item.size,item.quantity-1)}>−</button>{item.quantity}<button onClick={()=>c.update(item.slug,item.size,item.quantity+1)}>+</button></div><button onClick={()=>c.remove(item.slug,item.size)}>Remove</button></div><strong>{money(item.price*item.quantity)}</strong></div>)}</div><div className="cart-total"><div><span>Subtotal</span><b>{money(c.subtotal)}</b></div><p>Shipping calculated at checkout.</p><Link href="/checkout" onClick={()=>c.setCartOpen(false)}>Checkout ↗</Link><Link href="/cart" onClick={()=>c.setCartOpen(false)}>View bag</Link></div></>}</aside></div>}
<Footer/></>}
function Footer(){return <footer id="footer"><div className="footer-logo">ARCHIVE/SUPPLY</div><div><h4>Shop</h4><Link href="/new-drops">New drops</Link><Link href="/men">Men</Link><Link href="/women">Women</Link><Link href="/collections">Collections</Link></div><div><h4>Help</h4><Link href="/help">Shipping & returns</Link><Link href="/help#sizes">Size guide</Link><Link href="/contact">Contact</Link></div><div><h4>About</h4><Link href="/about">Our story</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><NewsletterForm source="footer"/></footer>}
