"use client";
import SubscribersPanel from "@/components/SubscribersPanel";
import InventoryPanel from "@/components/InventoryPanel";
import OrderDetails from "@/components/OrderDetails";
import ProductManager from "@/components/ProductManager";import Link from "next/link";import {useCallback,useEffect,useMemo,useState} from "react";import {money} from "@/data/products";
const statuses=["new","confirmed","preparing","shipped","delivered","cancelled"];
export default function Dashboard(){const [selectedId,setSelectedId]=useState(null);const [active,setActive]=useState("Overview");const [orders,setOrders]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/orders",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load orders");setOrders(body.orders)}catch(problem){setError(problem.message)}finally{setLoading(false)}},[]);useEffect(()=>{const task=setTimeout(()=>{load()},0);return()=>clearTimeout(task)},[load]);
 async function updateStatus(id,status){setError("");try{const response=await fetch(`/api/orders/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const body=await response.json();if(!response.ok)throw Error(body.error||"Unable to update order");setOrders(current=>current.map(order=>order._id===id?body.order:order))}catch(problem){setError(problem.message)}}
 const stats=useMemo(()=>{const delivered=orders.filter(order=>order.status==="delivered");return [{label:"COD revenue collected",value:money(delivered.reduce((sum,order)=>sum+order.total,0)),note:`${delivered.length} delivered`},{label:"Open orders",value:String(orders.filter(order=>!["delivered","cancelled"].includes(order.status)).length),note:"Requires action"},{label:"Awaiting confirmation",value:String(orders.filter(order=>order.status==="new").length),note:"Newest first"},{label:"Average order",value:money(orders.length?orders.reduce((sum,order)=>sum+order.total,0)/orders.length:0),note:"All COD orders"}]},[orders]);
 const selectedOrder=orders.find(order=>order._id===selectedId);
 const visible=orders.filter(order=>`${order.orderNumber} ${order.customer?.firstName} ${order.customer?.lastName} ${order.customer?.phone}`.toLowerCase().includes(query.toLowerCase()));
 return <main className="dashboard-shell"><aside className="dashboard-side"><div className="admin-brand">ARCHIVE/SUPPLY <span>OPS</span></div><p className="dashboard-label">Operations</p><nav>{["Overview","Orders","Products","Inventory","Subscribers"].map(item=><button className={active===item?"active":""} onClick={()=>setActive(item)} key={item}>{item}{item==="Orders"&&<b>{orders.length}</b>}</button>)}</nav><div className="side-bottom"><button onClick={async()=>{await fetch("/api/admin-session",{method:"DELETE"});location.reload()}}>Sign out</button><Link href="/">← Storefront</Link></div></aside><section className="dashboard-main"><header className="dashboard-header"><div><p className="dashboard-label">COD COMMERCE CONTROL</p><h1>{active}</h1></div><button className="refresh-button" onClick={load}>Refresh data ↻</button></header><div className="dashboard-content">{error&&<div className="admin-error" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}
 {active==="Overview"&&<><div className="stats-grid">{stats.map(stat=><article className="stat-card" key={stat.label}><p>{stat.label}</p><strong>{stat.value}</strong><span>{stat.note}</span></article>)}</div><section className="panel admin-recent"><div className="panel-head"><h2>Recent COD orders</h2><button onClick={()=>setActive("Orders")}>View all →</button></div><OrderTable orders={orders.slice(0,6)} loading={loading} updateStatus={updateStatus} onView={setSelectedId}/></section></>}
 {active==="Orders"&&<section className="panel orders-panel"><div className="panel-head"><div><h2>Orders</h2><p>{visible.length} results · cash on delivery</p></div><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search order, name or phone"/></div><OrderTable orders={visible} loading={loading} updateStatus={updateStatus} onView={setSelectedId}/></section>}
 {active==="Products"&&<ProductManager/>}
 {active==="Subscribers"&&<SubscribersPanel/>}
 {active==="Inventory"&&<InventoryPanel/>}
 {["Customers","Discounts","Settings"].includes(active)&&<section className="panel admin-empty"><span>MODULE / {active.toUpperCase()}</span><h2>{active}</h2><p>This operational module is ready for the next data integration. Orders, products, and inventory are active now.</p></section>}
 </div></section>{selectedOrder&&<OrderDetails order={selectedOrder} onClose={()=>setSelectedId(null)}/>}</main>}
function OrderTable({orders,loading,updateStatus,onView}){if(loading)return <p className="admin-loading">Loading orders…</p>;if(!orders.length)return <p className="admin-loading">No COD orders yet. New checkout orders will appear here.</p>;return <div className="order-table"><div className="order-table-head"><span>Order</span><span>Customer</span><span>Items</span><span>Total</span><span>Payment</span><span>Status</span></div>{orders.map(order=><article key={order._id}><div><button className="order-detail-trigger" onClick={()=>onView(order._id)} aria-label={`View details for order ${order.orderNumber}`}>{order.orderNumber}<span>View details →</span></button><time>{new Date(order.createdAt).toLocaleDateString()}</time></div><div><b>{order.customer.firstName} {order.customer.lastName}</b><span>{order.customer.phone}<br/>{order.shipping.city}</span></div><span>{order.items.reduce((sum,item)=>sum+item.quantity,0)} pairs</span><b>{money(order.total)}</b><span className={`payment ${order.paymentStatus}`}>{order.paymentStatus}</span><select aria-label={`Status for ${order.orderNumber}`} disabled={["delivered","cancelled"].includes(order.status)} value={order.status} onChange={event=>updateStatus(order._id,event.target.value)}>{statuses.map(status=><option value={status} key={status}>{status}</option>)}</select></article>)}</div>}
